// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9L9OneVgtTyRmEd-ONtP93F2_2lYjjH0',
    appId: '1:130753715500:web:90d3e1301d1c6e4101e089',
    messagingSenderId: '130753715500',
    projectId: 'dj-sany',
    authDomain: 'dj-sany.firebaseapp.com',
    storageBucket: 'dj-sany.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHulXFEFfKiRlDQI-3iBapJL-gcdMeyG4',
    appId: '1:130753715500:android:09e843be0178f70001e089',
    messagingSenderId: '130753715500',
    projectId: 'dj-sany',
    storageBucket: 'dj-sany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4yP98jj_seNxISevVfs96dGqy4tDZqFY',
    appId: '1:130753715500:ios:84f1f4051e5554a501e089',
    messagingSenderId: '130753715500',
    projectId: 'dj-sany',
    storageBucket: 'dj-sany.appspot.com',
    iosClientId: '130753715500-diihdojqk6srbbropvp1ieri1esukevi.apps.googleusercontent.com',
    iosBundleId: 'dj.sany.mypfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4yP98jj_seNxISevVfs96dGqy4tDZqFY',
    appId: '1:130753715500:ios:2c998c7d782a08b401e089',
    messagingSenderId: '130753715500',
    projectId: 'dj-sany',
    storageBucket: 'dj-sany.appspot.com',
    iosClientId: '130753715500-2ct0d4d12denu1loca0b3vc2o0p29ora.apps.googleusercontent.com',
    iosBundleId: 'dj.sany.mypfe.RunnerTests',
  );
}
